<div id="good-wrap">
<div id="header-left">
	<h1>Terms of Use</h1>
</div>
<div id="header-right">
	<div id="util-sub-nav">
		<a class="footer_link" id="f_privacy" href="{$site_url}/info/privacy"><span class="i">Privacy Policy</span></a> &nbsp;|&nbsp;
		<a class="footer_link" id="f_terms" href="{$site_url}/info/terms"><span class="i">Terms of Use</span></a> &nbsp;|&nbsp;
		<a class="footer_link" id="f_faq" href="{$site_url}/info/faq"><span class="i">FAQs and Pricing</span></a> &nbsp;|&nbsp;
		<a class="footer_link" id="f_contact" href="{$site_url}/info/contact"><span class="i">Contact Us</span></a>
	</div>
</div>
<div class="clear"></div>

<p>We want to make it easier for you to accept payments and have developed a payments service (the "Service"). This PayPhoneAPP User Agreement ("Agreement") is a legal agreement between you ("you," "your") and PayPhoneAPP, Inc. ("PayPhoneAPP," "we," "our" or "us"). This Agreement is divided into two parts. Part one explains all of the terms that govern your use of the payment processing Service. Part two contains additional legal terms, including provisions that limit our liability to you and govern any potential legal dispute. In order to use the Service, you must accept all of the terms of this Agreement.</p>

<h2 class="subhead">Part One: Terms Governing Use of the Service</h2>

<h3>1. PayPhoneAPP Account Registration</h3>
<p>You must register with PayPhoneAPP ("PayPhoneAPP Account") in order to use the Service. Our registration process will ask you for certain information including your name and other personal information. You must provide accurate and complete information in response to our questions. You must also keep the information that you provide up-to-date.</p>
<p>Both individuals and businesses may register for a PayPhoneAPP Account. In the case of a company, partnership or other legally recognized business, you must provide accurate and complete information about yourself as well as the business. You can only sign-up to use the Service on behalf of a legally recognized business if you are authorized to act on behalf of the business and have the authority to bind the business to this Agreement. In order to sign up a business to use the Service, you must agree to this Agreement on behalf of the business. If you have so agreed, "you" means you, the natural person, as well as the business.</p>

<h3>2. User Name</h3>
<p>You must choose a reasonably descriptive user name that clearly identifies you or your business. This name will appear on the Payer's credit or debit card statement. If a transaction dispute results from your failure to use a reasonably descriptive user name, you agree to indemnify PayPhoneAPP for any costs stemming from such dispute.</p>

<h3>3. Software</h3>
<p>The PayPhoneAPP software is part of the Service. Among other things, the software enables you to access and use the Service. When you install the software, you will be asked to create your user profile and to establish a PayPhoneAPP Account on the PayPhoneAPP website or on your mobile device. You must complete this and other processes in order to access any funds that you accept through the Service. You must install any and all software updates to continue to use the Service.</p>

<h3>4. Verification and Inspection</h3>
<p>If your request to open a PayPhoneAPP Account is approved, PayPhoneAPP may request additional information from you at any time. PayPhoneAPP may ask you to present invoices from your suppliers, a government issued identification such as a passport or driver's license, or a business license. PayPhoneAPP may also ask for permission to inspect your business location. If you refuse any of these requests, your PayPhoneAPP Account may be terminated. We reserve the right to suspend or terminate the PayPhoneAPP Account of any user who provides inaccurate, untrue, or incomplete information, or fails to comply with the account registration requirements.</p>

<h3>5. Compatible Mobile Devices and Third Party Carrier Fees</h3>
<p>Your PayPhoneAPP Account enables you to submit or accept payment card transactions using a combination of compatible devices. Mobile devices modified contrary to the manufacturer's software or hardware guidelines, including but not limited to disabling hardware or software controls -- sometimes referred to as "jailbreaking" --are not compatible mobile devices. You acknowledge that the use of a modified device to use the Service is expressly prohibited, constitutes a violation of the terms of this agreement, and is grounds for termination of your PayPhoneAPP Account. PayPhoneAPP does not warrant that the Service will be compatible with your mobile device.</p>

<h3>6. Your PayPhoneAPP Account</h3>
<p>By creating a PayPhoneAPP Account, you confirm that you are either a legal resident of Canada, a Canadian citizen or a business entity authorized to conduct business by the Province and municipality in which it operates. The Service and your PayPhoneAPP Account may only be used in Canada.</p>
<p>By creating a PayPhoneAPP Account, you also confirm that you will not accept payments in connection with the following businesses or business activities: (1) any illegal activity, (2) buyers or membership clubs, (3) credit counseling or repair agencies, (4) credit protection or identity theft protection services, (5) direct marketing or subscription offers or services, (6) infomercial sales, (7) internet/mail order/telephone order pharmacies or pharmacy referral services (where fulfillment of medication is performed with an internet or telephone consultation, absent a physical visit with a physician including re-importation of pharmaceuticals from foreign countries), (8) multi-level marketing businesses, (9) inbound or outbound telemarketers, (10) firearms or ammunition, (11) rebate based businesses, (12) up-sell merchants, (13) bill payment services, (14) betting, including lottery tickets, casino gaming chips, off-track betting, and wagers at races, (15) financial institutions offering manual or automated cash disbursements, (16) financial institutions offering merchandise and services, (17) sales of money-orders or foreign currency by non-financial institutions, (18) wire transfer money orders, (19) high-risk merchants, including telemarketing merchants, (20) service station merchants, (21) automated fuel dispensers, (22) adult entertainment oriented products or services (in any medium, e.g., internet, telephone or printed material), (23) internet/mail order/telephone order firearm or weapon sales, (24) internet/mail order/telephone order cigarette or tobacco sales, (25) drug paraphernalia, (26) occult materials, (27) hate products, (28) escort services, and (29) bankruptcy attorneys.</p>
<p>By accepting this Agreement you confirm that you will satisfy these requirements.</p>

<h3>7. Our Role</h3>
<p>Our Service allows you to submit and/or accept payments. We are not a bank or a money services business ("MSB") and we do not offer banking or MSB services as defined by the United States Department of Treasury.</p>
<p>We work with your merchant payment processor to facilitate payments between two entities. This means that we collect, analyze and relay information generated in connection with these payments. We do not process the transactions, hold or release funds.</p>
<p>In order to serve in this role, we must enter into agreements with Networks,  processors and banks. These third parties require that our users enter into an agreement with one of our partner gateways. We will provide you a "Commercial Entity Agreement" that you must complete in order to use the Service. This may happen during the registration process or at some other time. If you fail to complete a "Commercial Entity Agreement," we may suspend or terminate your PayPhoneAPP Account.</p>

<h3>8. Your Authorization</h3>
<p>By accepting the terms of this Agreement, you authorize us to facilitate transactions on your behalf.  Your authorizations will remain in full force and effect until your PayPhoneAPP Account is closed or terminated.</p>

<h3>9. Restricted Use</h3>
<p>You may use this Service only to the extent that you obey all laws, rules, and regulations applicable to your use of the Service. You may not act as a payment intermediary, aggregator or service bureau or otherwise resell our services on behalf of any third party. This means that you may not use the Service to handle, process or transmit funds for any third party. You also may not use the Service to process cash advances.</p>

<h3>10. Unauthorized or Illegal Use</h3>
<p>We may decide not to facilitate any transaction that you submit to us if we believe that the transaction is in violation of any part of this agreement, or exposes you, other PayPhoneAPP users, our processors or PayPhoneAPP to harm. Harm includes fraud and other criminal acts. If we reasonably suspect that your PayPhoneAPP Account has been used for an unauthorized, illegal, or criminal purpose, you give us express authorization to share information about you, your PayPhoneAPP Account, and any of your transactions with law enforcement.</p>

<h3>11. Accepted Cards</h3>
<p>PayPhoneAPP works with any credit, pre-paid, or gift cards with a Visa, MasterCard, American Express, or Discover logo. We may remove or add Credit Accounts that we accept at anytime without prior notice. </p>

<h3>12. Applicable Network Rules</h3>
<p>The Networks require that you and PayPhoneAPP comply with all applicable bylaws, rules, and regulations ("Network Rules"). The Networks have historically reserved the right to amend their rules and regulations. PayPhoneAPP may be required to change this agreement in connection with amendments to the Network Rules. 
Network Rules currently prohibit you from (a) assessing a surcharge for the use of a Card in connection with any transaction, or (b) dispensing cash on any Card transaction. The Rules also restrict your use of Network logos to indicating your acceptance of the Network cards and to other uses expressly authorized by the Networks.</p>

<h3>13. Underwriting</h3>
<p>PayPhoneAPP will review some or all of the information that you submit in connection with your request to sign up for the Service. PayPhoneAPP may forward such information on to its processor(s) and/or partner gateway(s). In order to be eligible to use the Service, you must agree that PayPhoneAPP may share information about you and your PayPhoneAPP Account to its processor and/or partner gateway(s). After you submit your application, PayPhoneAPP or its processor may conclude that you will not be permitted to accept the PayPhoneAPP Service.</p>
<p>By accepting the terms of this Agreement, you specifically authorize PayPhoneAPP to request identity verifying information about you, including a consumer report that contains your name and address. PayPhoneAPP may periodically obtain additional reports to determine whether you continue to meet the requirements for a PayPhoneAPP Account.</p>
<p>You agree that PayPhoneAPP is permitted to contact and share information about you and your application (including whether you are approved or declined), and your PayPhoneAPP Account with your bank or other financial institution. This includes sharing information (a) about your transactions for regulatory or compliance purposes, (b) for use in connection with the management and maintenance of the service, (c) to create and update their customer records about you and to assist them in better serving you, and (d) to conduct PayPhoneAPP's risk management process.</p>

<h3>14. Our Fees</h3>
<p>You agree to pay the applicable fees listed on our Fee Schedule ("Fees") whenever you use our Service. Subject to the terms of this Agreement, we reserve the right to change our Fees. If we change our Fees, we will give you thirty (30) days notice of any change. You will not be permitted to continue to use the Service unless you consent to the change in Fees. To withdraw your consent, you will need to close your PayPhoneAPP Account. All Fees, charges, and payments facilitated through the Service are denominated in CAD dollars.</p>

<h3>15. Access to Funds</h3>
<p>Subject to the payout schedule identified below, your merchant account provider  will deposit to your account the amounts actually received for transactions submitted through the Service (less any applicable Fees). Once your bank account information is verified, your merchant account provider will automatically deposit your money in your designated bank account when your balance exceeds $10.</p>
<p>In the event that you do not have an ACH-enabled bank account, you may request a physical check. Check requests will be subject to a processing fee and an identity verification process.</p>
<p>Funds for any given transaction will not be deposited until the transaction is deemed complete. You are responsible for monitoring your transactions and ensuring that  payments to you are correct. You must notify your merchant account provider  of any errors in payments made to you within sixty (60) days of the error first appearing on your electronic transaction history. Failure to notify us of such an error will be deemed a waiver of any right to amounts owed to you.</p>

<h3>16. Payout Schedule</h3>
<p>Once you validate your bank account, your merchant account provider  will automatically initiate a payout to your bank account at the end of every business day. Payouts to your bank account will normally register in your account within 4-5 business days.</p>

<h3>16.1. New Accounts</h3>
<p>For new accounts likely to exceed $1,000 in sales per week, contact your merchant account provider   to inquire about accelerating your payout schedule. </p>

<h3>17. Availability of Funds</h3>
<p>Should PayPhoneAPP need to conduct an investigation or resolve any pending dispute related to your PayPhoneAPP Account, your merchant account provider  may defer payout or restrict access to your funds for the entire time it takes for us to do so. Your merchant account provider  also may defer payout or restrict access to your funds as required by law or court order, or if otherwise requested by law enforcement or governmental entity.</p>

<h3>18. PayPhoneAPP Account History</h3>
<p>When a payment is made to your bank account, we will update your PayPhoneAPP Account activity on the website and provide you a transaction confirmation. The confirmation will serve as your receipt. Summaries of your PayPhoneAPP Account activity, including monthly statements, are available on our website for up to one year of account activity. Except as required by law, you are solely responsible for (a) compiling and retaining permanent records of all transactions and other data associated with your PayPhoneAPP Account and your use of the Service, and (b) reconciling all transactional information that is associated with your PayPhoneAPP Account. If you believe that there is an error or unauthorized transaction activity is associated with your PayPhoneAPP Account, you agree to contact us immediately.</p>

<h3>19. Reserve</h3>
<p>At any time and from time to time, your merchant account provider  may temporarily suspend or delay payments to you and/or designate an amount of funds that we must maintain in a separate reserve account (a "Reserve") to secure the performance of your payment obligations under this Agreement. Your merchant account provider  may require a Reserve for any reason, including if you have a high rate of Chargebacks (described in Section 25), refunds, or other indications of performance problems related to your use of the Service. The Reserve will be in an amount as reasonably determined by your merchant account provider  to cover anticipated Chargebacks, returns, unshipped merchandise and/or unfulfilled services or credit risk based on your processing history or such amount designated by our processor. The Reserve may be raised, reduced or removed at any time by your merchant account provider, in its sole discretion, based on your payment history, a credit review, the amount of any arbitration award or court judgment against you in your merchant account provider's favor, or otherwise as PayPhoneAPP or your merchant account provider may determine or require. If you do not have sufficient funds in your Reserve, your merchant account provider  may fund the Reserve from any funding source associated with your PayPhoneAPP Account, including but not limited to any funds (a) due to you under this Agreement, or (b) available in your bank account, or other payment instrument registered with your merchant account provider. You grant your merchant account provider  a security interest in and lien on any and all funds held in any Reserve, and also authorize your merchant account provider  to make any withdrawals or debits from the Reserve, without prior notice to you, to collect amounts that you owe us under this Agreement, including without limitation for any reversals of deposits or transfers made to your bank account. </p>

<h3>20. Receipts</h3>
<p>When your customer is present at the time of the transaction and signs the physical receipt, you benefit from the Payment Network rules for card present transactions. You agree to request that your customer personally sign for all transactions greater than $25.00 when your customer is present. You must make a written receipt available to your customers for any transaction greater than fifteen dollars ($15.00). You may give your customers the option to receive or decline a written receipt. As a convenience, but not in lieu of a written receipt, you may also offer PayPhoneAPP electronic receipts for delivery through the app to your customers.</p>

<h3>21. Taxes</h3>
<p>You are responsible for determining any and all taxes assessed, incurred, or required to be collected, paid, or withheld for any reason in connection your use of our software and services ("Taxes"). You also are solely responsible for collecting, withholding, reporting, and remitting correct Taxes to the appropriate tax authority. We are not obligated to, nor will we determine whether Taxes apply, or calculate, collect, report, or remit any Taxes to any tax authority arising from any transaction.</p>

<h3>22. Customer Service</h3>
<p>You are solely responsible for all customer service issues relating to your goods or services, including pricing, order fulfillment, order cancellation by you or customer, returns, refunds and adjustments, rebates, functionality and warranty, technical support, and feedback concerning experiences with your personnel, policies or processes. In performing customer service, you will always present yourself as a separate entity from us. As between you and us, we are solely responsible for customer service issues relating to any PayPhoneAPP Account, your merchant account provider  is responsible for issues relating to payment, card processing, debiting or crediting.</p>

<h3>23. Refunds and Returns</h3>
<p>By using PayPhoneAPP, you agree to process returns of, and provide refunds and adjustments for, your goods or services through your merchant account provider  in accordance with this Agreement and Network Rules. Network Rules require that you will (a) maintain a fair return, cancellation or adjustment policy; (b) disclose your return or cancellation policy to customers at the time of purchase, (c) not give cash refunds to a customer in connection with a Card sale, unless required by law, and (d) not accept cash or any other item of value for preparing a Card sale refund. The amount of the refund/adjustment must include any associated taxes required to be refunded and cannot exceed the amount shown as the total on the original sales data except by the exact amount required to reimburse the customer for postage that the customer paid to return merchandise. If you accept returns and are making an uneven exchange of merchandise (e.g., the sales price is not the same), you must issue a credit for the total amount of the merchandise being returned and complete a new sale for any new merchandise. Please be aware, if your refund policy prohibits returns or is unsatisfactory to the buyer, you may still receive a Chargeback relating to such sales.  If you choose to cancel your PayPhoneAPP account, you will be charged for the current month's service only.</p>
<h3>24. Your Liability for Chargebacks</h3>
<p>The amount of a transaction may be reversed (a "Chargeback") if the transaction (a) is disputed, (b) is reversed for any reason by the Network, our processor, your merchant account provider, or a Payer's or our financial institution, (c) was not authorized or we have any reason to believe that the transaction was not authorized, or (d) is allegedly unlawful, suspicious, or in violation of the terms of this Agreement.</p>

<h3>25.  Collection Rights for Chargebacks</h3>
<p>For any transaction that results in a Chargeback, your merchant account provider may withhold the Chargeback amount in a Reserve. Your merchant account provider may deduct the amount of any Chargeback and any associated Fees, fines, or penalties listed in the Fee Schedule  (including without limitation any Reserve), any proceeds due to you, your bank account, or other payment instrument registered with us. If you have pending Chargebacks, we may delay payouts. Further, if we reasonably believe that a Chargeback is likely with respect to any transaction, your merchant account provider may withhold the amount of the potential Chargeback from payments otherwise due to you under this Agreement until such time that: (a) a Chargeback is assessed due to a customer's complaint, in which case your merchant account provider will retain the funds; (b) the period of time under applicable law or regulation by which the customer may dispute that the transaction has expired; or (c) your merchant account provider determines that a Chargeback on the transaction will not occur. If your merchant account provider is unable to recover funds related to a Chargeback for which you are liable, you will pay the full amount of the Chargeback immediately upon demand. You agree to pay all costs and expenses, including without limitation attorneys' fees and other legal expenses, incurred by or on behalf of PayPhoneAPP or your merchant account provider in connection with the collection of all deficit balances unpaid by you.</p>

<h3>26. Excessive Chargebacks</h3>
<p>If your merchant account provider determines that you are incurring an excessive amount of Chargebacks, they may establish controls or conditions governing your PayPhoneAPP Account, including without limitation, by (a) establishing new processing fees, (b) creating a Reserve in an amount reasonably determined by your merchant account provider to cover anticipated Chargebacks and related fees, (c) delaying payouts, and (d) terminating or suspending the Service.</p>

<h3>27. Contesting Chargebacks</h3>
<p>You agree to assist us when requested, at your expense, to investigate any of your transactions processed through the Service. To that end, you permit us to share information about a Chargeback with the payer, the payer's financial institution, and your financial institution in order to investigate and/or mediate a Chargeback. We will request necessary information from you to contest the Chargeback. If the Chargeback is contested successfully, your merchant account provider will release the reserved funds. If a Chargeback dispute is not resolved in your favor or you choose not to contest the Chargeback, your merchant account provider may recover the Chargeback amount and any associated fees as described in this Agreement. You acknowledge that your failure to assist us in a timely manner when investigating a transaction, including providing necessary documentation within fifteen (15) days of our request, may result in an irreversible Chargeback. Your merchant account provider reserves the right, upon notice to you, to charge a fee for mediating and/or investigating Chargeback disputes.</p>

<h3>28. Dormant PayPhoneAPP Accounts</h3>
<p>If there is no activity in your PayPhoneAPP Account (including access or payment transactions) for at least two (2) years, consecutively, and you have a Balance, we will notify you by sending an email to your registered email address and give you the option of keeping your PayPhoneAPP Account open. If you do not respond to our notice within thirty (30) days, we will automatically close your PayPhoneAPP Account.</p>

<h3>29. PayPhoneAPP Processing Errors</h3>
<p>We will attempt to rectify processing errors that we discover. If the error resulted in your receipt of less than the correct amount to which you were entitled, PayPhoneAPP will credit your bank account for the difference. If the error results in your receipt of more than the correct amount to which you were entitled, PayPhoneAPP will debit the extra funds from your bank account via your merchant account provider. PayPhoneAPP will only correct transactions that you process incorrectly if and when you notify us of such an error. Your failure to notify us of a processing error within thirty (30) days of when it first appears on your electronic transaction history will be deemed a waiver of any right to amounts owed to you.</p>

<h3>30. Your Privacy</h3>
<p>Your privacy is very important to PayPhoneAPP. Upon acceptance of this Agreement you confirm that you have read, understood and accepted PayPhoneAPP's Privacy Policy.</p>

<h3>31. Privacy of Others</h3>
<p>By using the Service, you may receive information about Payers or other users. You must keep such information confidential and only use it in connection with the Service. You may not disclose or distribute any such information to a third party or use the information for marketing purposes unless you receive the express consent of the user.</p>

<h3>32. Disclosures and Notices</h3>
<p>You agree that PayPhoneAPP can provide Disclosures and Notices required by law and other information about your PayPhoneAPP Account to you electronically by posting it on our website, or emailing it to the email address listed in your PayPhoneAPP Account. You also agree that electronic Disclosures and Notices have the same meaning and effect as if we had provided you with a paper copy. Such Disclosures and Notices are considered received by you within 24 hours of the time it was posted to our website, or emailed to you unless we receive notice that the email was not delivered.</p>

<h3>33. Security</h3>
<p>We have implemented technical and organizational measures designed to secure your personal information from accidental loss and from unauthorized access, use, alteration or disclosure. However, we cannot guarantee that unauthorized third parties will never be able to defeat those measures or use your personal information for improper purposes. You acknowledge that you provide your personal information at your own risk.</p>

<h3>34. Termination</h3>
<p>If your PayPhoneAPP Account is terminated for any reason or no reason, you agree: (a) to continue to be bound by this Agreement, (b) to immediately stop using the Service, (c) that the license provided under this Agreement shall end, (d) that we reserve the right (but have no obligation) to delete all of your information and account data stored on our servers, and (e) that PayPhoneAPP shall not be liable to you or any third party for termination of access to the Service or deletion of your information or account data.</p>

<h3>35. Your Right to Terminate</h3>
<p>You may terminate this Agreement and other PayPhoneAPP agreements by closing your PayPhoneAPP Account at any time. Upon closure of a PayPhoneAPP Account, any pending transactions will be cancelled. </p>

<h3>36. Suspension or Termination by Us</h3>
<p>We may terminate this Agreement and close your PayPhoneAPP Account for any reason or no reason at any time upon notice to you. We may also suspend the Service and access to your PayPhoneAPP Account if you (a) have violated the terms of the PayPhoneAPP agreements and policies or this Agreement, (b) pose an unacceptable credit or fraud risk to us, or (c) provide any false, incomplete, inaccurate, or misleading information or otherwise engage in fraudulent or illegal conduct.</p>

<h3>37. Effect of Termination</h3>
<p>We will not be liable to you for compensation, reimbursement, or damages in connection with your use of the Service, or any termination or suspension of the Service. Any termination of this Agreement does not relieve you of any obligations to pay any Fees or costs accrued prior to the termination and any other amounts owed by you to your merchant account provider as provided in this Agreement.</p>

<h2 class="subhead">Part Two: Additional Legal Terms</h2>

<h3>38. Your License</h3>
<p>PayPhoneAPP grants you a personal, limited, non-exclusive, revocable, non-transferable license, without the right to sublicense, to electronically access and use the Service solely to submit and/or receive payments and to manage the funds you so receive. The Service includes our website, any software, programs, documentation, tools, internet-based services, components, and any updates (including software maintenance, service information, help content, bug fixes or maintenance releases) thereto provided to you by PayPhoneAPP. You will be entitled to download updates to the Service, subject to any additional terms made known to you at that time, when PayPhoneAPP makes these updates available.</p>
<p>You may not, nor may you permit any third party to do any of the following: (i) access or attempt to access PayPhoneAPP systems, programs or data that are not made available for public use: (ii) copy, reproduce, republish, upload, post, transmit, resell or distribute in any way material from PayPhoneAPP; (iii) permit any third party to use and benefit from the Service via a rental, lease, timesharing, service bureau or other arrangement; (iv) transfer any rights granted to you under this Agreement; (v) work around any of the technical limitations of the Service, use any tool to enable features or functionality that are otherwise disabled in the Service, or decompile, disassemble or otherwise reverse engineer the Service, except to the extent that such restriction is expressly prohibited by law; (vi) perform or attempt to perform any actions that would interfere with the proper working of the Service, prevent access to or use of the Service by our other users, or impose an unreasonable or disproportionately large load on our infrastructure; or (vii) otherwise use the Service except as expressly allowed under this section.</p>

<h3>39. Ownership</h3>
<p>The Service is licensed and not sold. PayPhoneAPP reserves all rights not expressly granted to you in this Agreement. The Service is protected by patent pending, copyright, trade secret and other intellectual property laws. PayPhoneAPP owns the title, copyright and other worldwide Intellectual Property Rights (as defined below) in the Service and all copies of the Service. This Agreement does not grant you any rights to PayPhoneAPP's trademarks or service marks.</p>
<p>For the purposes of this Agreement, "Intellectual Property Rights" means all patent rights, copyright rights, mask work rights, moral rights, rights of publicity, trademark, trade dress and service mark rights, goodwill, trade secret rights and other intellectual property rights as may now exist or hereafter come into existence, and all applications therefore and registrations, renewals and extensions thereof, under the laws of any province, state, country, territory or other jurisdiction.</p>
<p>You may choose to or we may invite you to submit comments or ideas about the Service, including without limitation about how to improve the Service or our products ("Ideas"). By submitting any Idea, you agree that your disclosure is gratuitous, unsolicited and without restriction and will not place PayPhoneAPP under any fiduciary or other obligation, and that we are free to use the Idea without any additional compensation to you, and/or to disclose the Idea on a non-confidential basis or otherwise to anyone. You further acknowledge that, by acceptance of your submission, PayPhoneAPP does not waive any rights to use similar or related ideas previously known to PayPhoneAPP, or developed by its employees, or obtained from sources other than you.</p>

<h3>40. Indemnity</h3>
<p>You will indemnify, defend and hold us and our processors harmless (and our respective employees, directors, agents, affiliates and representatives) from and against any and all claims, costs, losses, damages, judgments, Tax assessments, penalties, interest, and expenses (including without limitation reasonable attorneys' fees) arising out of any claim, action, audit, investigation, inquiry, or other proceeding instituted by a person or entity that arises out of or relates to: (a) any actual or alleged breach of your representations, warranties, or obligations set forth in this Agreement, including without limitation any violation of our Policies or the Networks' rules; (b) your wrongful or improper use of the Service; (c) any transaction submitted by you through the Service (including without limitation the accuracy of any Product Information that you provide or any claim or dispute arising out of products or services offered or sold by you); (d) your violation of any third-party right, including without limitation any right of privacy, publicity rights or Intellectual Property Rights; (e) your violation of any law, rule or regulation of Canada, the United States or any other country; (f) any other party's access and/or use of the Service with your unique username, password or other appropriate security code.</p>

<h3>41. Representation and Warranties</h3>
<p>You represent and warrant to us that: (a) you are at least eighteen (18) years of age; (b) you are eligible to register and use the Service and have the right, power, and ability to enter into and perform under this Agreement; (c) the name identified by you when you registered is your name or business name under which you sell goods and services; (d) any sales transaction submitted by you will represent a bona fide sale by you; (e) any sales transactions submitted by you will accurately describe the goods and/or services sold and delivered to a purchaser; (f) you will fulfill all of your obligations to each customer for which you submit a transaction and will resolve any consumer dispute or complaint directly with the purchaser; (g) you and all transactions initiated by you will comply with all federal, provincial, state, and local laws, rules, and regulations applicable to your business, including any applicable tax laws and regulations; (h) except in the ordinary course of business, no sales transaction submitted by you through the Service will represent a sale to any principal, partner, proprietor, or owner of your entity; (i) you will not use the Service, directly or indirectly, for any fraudulent undertaking or in any manner so as to interfere with the use of the Service.</p>

<h3>42. No Warranties</h3>
<p>THE SERVICE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. USE OF THE SERVICE IS AT YOUR OWN RISK. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE SERVICE IS PROVIDED WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM COMPANY OR THROUGH THE SERVICE WILL CREATE ANY WARRANTY NOT EXPRESSLY STATED HEREIN. WITHOUT LIMITING THE FOREGOING, PAYPHONEAPP, ITS PROCESSORS, ITS PROVIDERS, ITS LICENSORS (AND THEIR RESPECTIVE SUBSIDIARIES, AFFILIATES, AGENTS, DIRECTORS, AND EMPLOYEES) DO NOT WARRANT THAT THE CONTENT IS ACCURATE, RELIABLE OR CORRECT; THAT THE SERVICE WILL MEET YOUR REQUIREMENTS; THAT THE SERVICE WILL BE AVAILABLE AT ANY PARTICULAR TIME OR LOCATION, UNINTERRUPTED OR SECURE; THAT ANY DEFECTS OR ERRORS WILL BE CORRECTED; OR THAT THE SERVICE IS FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. ANY CONTENT DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE SERVICE IS DOWNLOADED AT YOUR OWN RISK AND YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR PROPERTY OR LOSS OF DATA THAT RESULTS FROM SUCH DOWNLOAD.</p>
<p>PAYPHONEAPP DOES NOT WARRANT, ENDORSE, GUARANTEE, OR ASSUME RESPONSIBILITY FOR ANY PRODUCT OR SERVICE ADVERTISED OR OFFERED BY A THIRD PARTY THROUGH THE SERVICE OR ANY HYPERLINKED WEBSITE OR SERVICE, OR FEATURED IN ANY BANNER OR OTHER ADVERTISING, AND PAYPHONEAPP WILL NOT BE A PARTY TO OR IN ANY WAY MONITOR ANY TRANSACTION BETWEEN YOU AND THIRD-PARTY PROVIDERS OF PRODUCTS OR SERVICES.</p>

<h3>43. Limitation of Liability and Damages</h3>
<p>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL PAYPHONEAPP, ITS PROCESSORS, SUPPLIERS OR ITS LICENSORS (OR THEIR RESPECTIVE AFFILIATES, AGENTS, DIRECTORS AND EMPLOYEES) BE LIABLE FOR ANY DIRECT, INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES, INCLUDING WITHOUT LIMITATION DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSSES, THAT RESULT FROM THE USE OF, INABILITY TO USE, OR UNAVAILABILITY OF THE SERVICE. UNDER NO CIRCUMSTANCES WILL PAYPHONEAPP BE RESPONSIBLE FOR ANY DAMAGE, LOSS OR INJURY RESULTING FROM HACKING, TAMPERING OR OTHER UNAUTHORIZED ACCESS OR USE OF THE SERVICE OR YOUR PAYPHONEAPP ACCOUNT OR THE INFORMATION CONTAINED THEREIN.</p>
<p>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, PAYPHONEAPP AND ITS PROCESSORS (AND THEIR RESPECTIVE AFFILIATES, AGENTS, DIRECTORS, AND EMPLOYEES) ASSUME NO LIABILITY OR RESPONSIBILITY FOR ANY (I) ERRORS, MISTAKES, OR INACCURACIES OF CONTENT; (II) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO OR USE OF THE SERVICE; (III) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION STORED THEREIN; (IV) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM THE SERVICE; (V) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE THAT MAY BE TRANSMITTED TO OR THROUGH THE SERVICE BY ANY THIRD PARTY; (VI) ANY ERRORS OR OMISSIONS IN ANY CONTENT OR FOR ANY LOSS OR DAMAGE INCURRED AS A RESULT OF THE USE OF ANY CONTENT POSTED, EMAILED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE THROUGH THE SERVICE; AND/OR (VII) USER CONTENT OR THE DEFAMATORY, OFFENSIVE, OR ILLEGAL CONDUCT OF ANY THIRD PARTY. IN NO EVENT SHALL PAYPHONEAPP, ITS PROCESSORS, AGENTS, SUPPLIERS, OR LICENSORS (OR THEIR RESPECTIVE AFFILIATES, AGENTS, DIRECTORS, AND EMPLOYEES) BE LIABLE TO YOU FOR ANY CLAIMS, PROCEEDINGS, LIABILITIES, OBLIGATIONS, DAMAGES, LOSSES OR COSTS IN AN AMOUNT EXCEEDING THE AMOUNT OF FEES EARNED BY US IN CONNECTION WITH YOUR USE OF THE SERVICE DURING THE THREE (3) MONTH PERIOD IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO THE CLAIM FOR LIABILITY.</p>
<p>THIS LIMITATION OF LIABILITY SECTION APPLIES WHETHER THE ALLEGED LIABILITY IS BASED ON CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY, OR ANY OTHER BASIS, EVEN IF PAYPHONEAPP HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. THE FOREGOING LIMITATION OF LIABILITY SHALL APPLY TO THE FULLEST EXTENT PERMITTED BY LAW IN THE APPLICABLE JURISDICTION.</p>
<p>The Service is controlled and operated from its facilities in Canada. PayPhoneAPP makes no representations that the Service is appropriate or available for use in other locations. Those who access or use the Service from other jurisdictions do so at their own volition and are entirely responsible for compliance with all applicable Canadian and local laws and regulations, including but not limited to export and import regulations. You may not use the Service if you are a resident of a country embargoed by Canada, or are a foreign person or entity blocked or denied by the Canadian government. Unless otherwise explicitly stated, all materials found on the Service are solely directed to individuals, companies, or other entities located in Canada.</p>

<h3>44. Disputes</h3>
<p>Except as expressly provided in this Agreement, these terms are a complete statement of the agreement between you and PayPhoneAPP, and describe the entire liability of PayPhoneAPP and its vendors, partners and suppliers (including processors) and your exclusive remedy with respect to your access and use of the Service. If any provision of this Agreement is invalid or unenforceable under applicable law, then it shall be changed and interpreted to accomplish the objectives of such provision to the greatest extent possible under applicable law, and the remaining provisions will continue in full force and effect.</p>

<h3>45. Governing Law</h3>
<p>This Agreement will be governed by Canadian law as applied to agreements entered into and to be performed entirely within Canada, without regard to its choice of law or conflicts of law principles that would require application of law of a different jurisdiction, and applicable federal law. The parties hereby consent to the exclusive jurisdiction and venue in the Provincial courts in British Columbia. Headings are included for convenience only, and shall not be considered in interpreting this Agreement. The Agreement does not limit any rights that PayPhoneAPP may have under trade secret, copyright, patent or other laws. PayPhoneAPP's failure to assert any right or provision under this Agreement shall not constitute a waiver of such right or provision. No waiver of any term of this Agreement shall be deemed a further or continuing waiver of such term or any other term.</p>

<h3>46. Arbitration</h3>
<p>For any claim (excluding claims for injunctive or other equitable relief) where the total amount sought is less than $10,000.00 CAD, the party requesting relief may elect to resolve the dispute through binding non-appearance-based arbitration before a sole arbitrator and through an alternative dispute resolution (ADR) provider selected by the party initiating arbitration from a list of qualified providers maintained by PayPhoneAPP. The parties further agree that the prevailing party in the arbitration shall be entitled to recover its costs of arbitration or of any related court proceedings (including attorneys' fees and expenses), collection agency fees, and any applicable interest. The arbitrator's award shall be final and binding on the parties, who undertake to fulfill the terms of the award without delay. Judgment on the award may be entered in any court of competent jurisdiction.</p>

<h3>47. Limitation on Time to Sue</h3>
<p>Unless otherwise required by law, an action or proceeding by you to enforce an obligation, duty or right arising under this Agreement or by law must commence within one year after the cause of action accrues.</p>

<h3>48. Right to Amend</h3>
<p>We have the right to change or add to the terms of this Agreement at any time, and to change, delete, discontinue, or impose conditions on any feature or aspect of the Service with notice that we in our sole discretion deem to be reasonable in the circumstances, including such notice on our website at PayPhoneAPP.com or any other website maintained or owned by us for the purposes of providing services in terms of this Agreement. Any use of the Service after our publication of any such changes shall constitute your acceptance of this Agreement as modified.</p>

<h3>49. Assignment</h3>
<p>This Agreement, and any rights and licenses granted hereunder, may not be transferred or assigned by you, but may be assigned by PayPhoneAPP without restriction.</p>

<h3>50. Third Party Services and Links to Other Web Sites</h3>
<p>You may be offered services, products and promotions provided by third parties and not by PayPhoneAPP. If you decide to use these Third Party Services you will be responsible for reviewing and understanding the terms and conditions associated with these services. You agree that PayPhoneAPP is not responsible for the performance of these services. The PayPhoneAPP website may contain links to third party websites as a convenience to you. The inclusion of any website link does imply an approval, endorsement, or recommendation by PayPhoneAPP. You agree that you access any such website at your own risk, and that the site is not governed by the terms and conditions contained in this Agreement. PayPhoneAPP expressly disclaims any liability for these websites. Please remember that when you use a link to go from our website to another website, our Privacy Policy is no longer in effect. Your browsing and interaction on any other website, including those that have a link on our website, is subject to that website's own rules and policies.</p>

<h3>51. Modification of Terms of Use</h3>
<p>We have the right to change or add to the terms of this Agreement at any time, and to change, delete, discontinue, or impose conditions on any feature or aspect of the software or services with notice that we in our sole discretion deem to be reasonable in the circumstances, including notice on our website at PayPhoneAPP.com or any other website maintained or owned by us for the purposes of providing services in terms of this Agreement, and communicate to you. Any use of our software or services after our publication of any such changes shall constitute your acceptance of this Agreement as modified.</p>

<h3>52. Other Provisions</h3>
<p>Except as expressly provided in this Agreement, these terms are a complete statement of the agreement between you and PayPhoneAPP, with respect to the provision of payment facilitation services. In the event of a conflict between this Agreement and any other PayPhoneAPP agreement or policy, this Agreement shall prevail on the subject matter of this Agreement. If any provision of this Agreement is invalid or unenforceable under applicable law, then it shall be changed and interpreted to accomplish the objectives of such provision to the greatest extent possible under applicable law, and the remaining provisions will continue in full force and effect.</p>

<h3>53. Survival</h3>
<p>In addition to any provision that is reasonably necessary to accomplish or enforce the purpose of this Agreement, the following sections of this Agreement survive and remain in effect in accordance with their terms upon the termination of this Agreement: 6, 7, 13, 15-20, 24-29, 38-51.</p>
</div>